package com.yyhd.joke.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yyhd.joke.db.entity.CommentDigg;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMMENT_DIGG".
*/
public class CommentDiggDao extends AbstractDao<CommentDigg, String> {

    public static final String TABLENAME = "COMMENT_DIGG";

    /**
     * Properties of entity CommentDigg.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property DiggCount = new Property(1, int.class, "diggCount", false, "DIGG_COUNT");
        public final static Property IsDigged = new Property(2, boolean.class, "isDigged", false, "IS_DIGGED");
        public final static Property CommentPublicTime = new Property(3, long.class, "commentPublicTime", false, "COMMENT_PUBLIC_TIME");
    }


    public CommentDiggDao(DaoConfig config) {
        super(config);
    }
    
    public CommentDiggDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMMENT_DIGG\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"DIGG_COUNT\" INTEGER NOT NULL ," + // 1: diggCount
                "\"IS_DIGGED\" INTEGER NOT NULL ," + // 2: isDigged
                "\"COMMENT_PUBLIC_TIME\" INTEGER NOT NULL );"); // 3: commentPublicTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMMENT_DIGG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CommentDigg entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getDiggCount());
        stmt.bindLong(3, entity.getIsDigged() ? 1L: 0L);
        stmt.bindLong(4, entity.getCommentPublicTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CommentDigg entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getDiggCount());
        stmt.bindLong(3, entity.getIsDigged() ? 1L: 0L);
        stmt.bindLong(4, entity.getCommentPublicTime());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public CommentDigg readEntity(Cursor cursor, int offset) {
        CommentDigg entity = new CommentDigg( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.getInt(offset + 1), // diggCount
            cursor.getShort(offset + 2) != 0, // isDigged
            cursor.getLong(offset + 3) // commentPublicTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CommentDigg entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDiggCount(cursor.getInt(offset + 1));
        entity.setIsDigged(cursor.getShort(offset + 2) != 0);
        entity.setCommentPublicTime(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(CommentDigg entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(CommentDigg entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CommentDigg entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
