package com.yyhd.joke.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yyhd.joke.db.entity.CommentDigg;
import com.yyhd.joke.db.entity.JokeType;
import com.yyhd.joke.db.entity.LastWatchJoke;
import com.yyhd.joke.db.entity.UserInfo;

import com.yyhd.joke.greendao.dao.CommentDiggDao;
import com.yyhd.joke.greendao.dao.JokeTypeDao;
import com.yyhd.joke.greendao.dao.LastWatchJokeDao;
import com.yyhd.joke.greendao.dao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commentDiggDaoConfig;
    private final DaoConfig jokeTypeDaoConfig;
    private final DaoConfig lastWatchJokeDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final CommentDiggDao commentDiggDao;
    private final JokeTypeDao jokeTypeDao;
    private final LastWatchJokeDao lastWatchJokeDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commentDiggDaoConfig = daoConfigMap.get(CommentDiggDao.class).clone();
        commentDiggDaoConfig.initIdentityScope(type);

        jokeTypeDaoConfig = daoConfigMap.get(JokeTypeDao.class).clone();
        jokeTypeDaoConfig.initIdentityScope(type);

        lastWatchJokeDaoConfig = daoConfigMap.get(LastWatchJokeDao.class).clone();
        lastWatchJokeDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        commentDiggDao = new CommentDiggDao(commentDiggDaoConfig, this);
        jokeTypeDao = new JokeTypeDao(jokeTypeDaoConfig, this);
        lastWatchJokeDao = new LastWatchJokeDao(lastWatchJokeDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(CommentDigg.class, commentDiggDao);
        registerDao(JokeType.class, jokeTypeDao);
        registerDao(LastWatchJoke.class, lastWatchJokeDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        commentDiggDaoConfig.clearIdentityScope();
        jokeTypeDaoConfig.clearIdentityScope();
        lastWatchJokeDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public CommentDiggDao getCommentDiggDao() {
        return commentDiggDao;
    }

    public JokeTypeDao getJokeTypeDao() {
        return jokeTypeDao;
    }

    public LastWatchJokeDao getLastWatchJokeDao() {
        return lastWatchJokeDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
